#!/bin/sh

if [ "$1" == "-m" ]; then
    cmd="`pwd`/make $1 $2 $3 $4"
elif [ "$1" == "-c" ]; then
    cmd="`pwd`/clean"
#    rm -f /tmp/matchdata.md
elif [ "$1" == "-s" ]; then
    cmd="`pwd`/sdist"
else
    cmd="`pwd`/build $1 $2 $3 $4"
fi

quits()
{
    if [ $? -ne 0 ]; then
        cd ..
        exit 0
    fi
}

start=`pwd`
for i in "addutil" "libfreekick" "freekick_client" "freekick_server"; do
    cd $start/$i
    $cmd
    quits
    cd $start
done

